int layer0[44] = {
    KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_0, KEY_Y, KEY_U, KEY_I, KEY_O, KEY_P, 
    KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_0, KEY_H, KEY_J, KEY_K, KEY_L, KEY_SLASH, 
    KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, PRE_FUNCTION(1), KEY_N, KEY_M, KEY_COMMA, KEY_PERIOD, KEY_SEMICOLON, 
    KEY_ESC, KEY_TAB, KEYBOARD_LEFT_GUI, KEYBOARD_LEFT_CTRL, KEY_SPACE, KEYBOARD_LEFT_SHIFT, KEY_ENTER, KEYBOARD_RIGHT_ALT, KEY_MINUS, KEY_QUOTE, KEY_BACKSPACE };

int layer1[44] = {
    KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_0, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0, 
    SHIFT(KEY_TILDE), KEY_LEFT_BRACE, KEY_PAGE_UP, SHIFT(KEY_9), SHIFT(KEY_LEFT_BRACE), KEY_0, KEY_LEFT, KEY_DOWN, KEY_UP, KEY_RIGHT, SHIFT(KEY_BACKSLASH), 
    KEY_TILDE, KEY_RIGHT_BRACE, KEY_PAGE_DOWN, SHIFT(KEY_0), SHIFT(KEY_RIGHT_BRACE), PRE_FUNCTION(1), KEY_DELETE, KEY_BACKSLASH, KEY_EQUAL, SHIFT(KEY_EQUAL), KEY_INSERT,
    FUNCTION(2), KEYBOARD_RIGHT_SHIFT, KEYBOARD_LEFT_GUI, KEYBOARD_LEFT_CTRL, KEY_BACKSPACE, KEYBOARD_LEFT_SHIFT, KEY_ENTER, KEYBOARD_RIGHT_ALT, KEY_HOME, KEY_INSERT, KEY_END };

int layer2[44] = {
    KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_0, KEY_F1, KEY_F7, KEY_F8, KEY_F9, KEY_F10, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, KEY_F11, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, KEY_F12, 
    LAYER(0), 0, KEYBOARD_LEFT_GUI, KEYBOARD_LEFT_CTRL, KEY_SPACE, KEYBOARD_LEFT_SHIFT, KEY_ENTER, PRE_FUNCTION(1), 0, 0, FUNCTION(0) };

int *layers[] = {layer0, layer1, layer2};

#include "layout_common.h"
